Tello/Tello/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls',namespace = 'core')),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('api/v1/', include('accounts.api.urls')),
    path('api/v1/core/', include('core.api.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tello/accounts/urls.py
from django.urls import path
from core.views import *
from accounts.views import *
from django.contrib.auth.views import LogoutView

app_name = 'account'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('profile/<slug:slug>/', UserProfileView.as_view(), name='user-profile'),
    path('change-password/', UpdatePasswordView.as_view(), name='change-password'),
    path('wishlist/<slug:slug>/', UserWishlistView.as_view(), name='profile-favorites'),
    path('cart/<slug:slug>/', UserCartView.as_view(), name='cart'),
    path('create-order/<slug:slug>/', CreateOrderView.as_view(), name='create-order'),
    path('success/', SuccessPageView.as_view() ,name ='success'),
    path('register/', usersignup,name ='register'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate_account, name='activate'),
    path('log-out', LogoutView.as_view(), name='log-out'),
]

Tello/core/api/urls.py
from django.urls import path
from .views import *

app_name = 'core_api'

urlpatterns = [
    path('create-product-version/', ProductVersionAPIView.as_view(), name='create-product-version'),
    
]

Tello/core/urls.py
from django.urls import path
from core.views import *
# from django.contrib.auth.views import LogoutView

app_name = 'core'

urlpatterns = [
    path('',MainPageView.as_view(),name ='main'),
    path('products/',ProductListView.as_view(),name ='products'),
    path('product/<slug:slug>', ProductDetailView.as_view(), name='product'),
    path('faq/', FAQView.as_view(), name='faq'),
]

Tello/core/models.py
from django.db import models
from .common import slugify
from accounts.models import *

class Product(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField('Description')
    price = models.DecimalField('Price',max_digits=6, decimal_places=2)
    brand = models.CharField(max_length=100)
    form_factor = models.CharField(max_length=100)
    # operating_system = models.CharField(max_length=100, null=True, blank=True)
    # cellular_technology = models.CharField(max_length=100, null=True, blank=True)
    # display_type = models.CharField(max_length=100, null=True, blank=True)
    # camera = models.CharField(max_length=100, null=True, blank=True)
    # cpu = models.CharField(max_length=100, null=True, blank=True)
    # ram = models.CharField(max_length=100, null=True, blank=True)
    # battery = models.CharField(max_length=100, null=True, blank=True)
    # water_and_dust_rating = models.CharField(max_length=100, null=True, blank=True)
    # guarantee = models.CharField(max_length=100, null=True, blank=True)
    # storage = models.ManyToManyField("Storage", verbose_name=("Storage"), db_index=True, related_name='storage_product', null=True, blank=True)
    category = models.ForeignKey("Category", on_delete=models.CASCADE, db_index=True, related_name='category_product', null=True, blank=True)
    color = models.ManyToManyField('Color',  verbose_name=("Color"), db_index=True, related_name="color_product", null=True, blank=True)
    slug = models.SlugField(max_length=255, null=True, blank=True)
    rating = models.IntegerField('Rating',blank=True,null=False)
    # wishlist = models.ForeignKey(Wishlist, on_delete=models.CASCADE, db_index=True, related_name='wishlist_products', null=True, blank=True)
    # cart = models.ForeignKey(Cart, on_delete=models.CASCADE, db_index=True, related_name='cart_products', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        super(Product, self).save(*args, **kwargs)
        self.slug = f'{slugify(self.title)}-{self.id}'
        super(Product, self).save(*args, **kwargs)

class ProductVersion(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, db_index=True, related_name='product_version', null=False, blank=True)
    color = models.CharField(max_length=100)
    storage = models.CharField(max_length=100)
    quantity = models.IntegerField('Quantity',blank=True,null=False)

    class Meta:
        verbose_name = 'Product Version'
        verbose_name_plural = 'Product Versions'

    def __str__(self):
        return f"{self.product.title}"

    def get_final_price(self):
        quantity = int(self.quantity)
        price = int(self.product.price)
        return quantity*price

class Category(models.Model):
    title = models.CharField('Title',max_length=50, null=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f"{self.title}" 


class Comment(models.Model):
    author_name = models.CharField('Author name',max_length=50, null=True)
    author_surname = models.CharField('Author surname',max_length=50, null=True)
    text = models.TextField('Text')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, db_index=True, related_name='product_comment', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return f"{self.text}" 

class Storage(models.Model):
    storage_size = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Storage'
        verbose_name_plural = 'Storages'

    def __str__(self):
        return f"{self.storage_size}" 


class Color(models.Model):
    color = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Color'
        verbose_name_plural = 'Colors'

    def __str__(self):
        return f"{self.color}" 


class ColorImage(models.Model):
    image = models.ImageField('Image',upload_to='images/', null=True, blank=True)
    color = models.ForeignKey('Color', on_delete=models.CASCADE, db_index=True, related_name='color_image', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Color Image'
        verbose_name_plural = 'Color Images'

    def __str__(self):
        return f"{self.image}" 


class Image(models.Model):
    image = models.ImageField('Image',upload_to='images/', null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, db_index=True, related_name='product_image', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Image'
        verbose_name_plural = 'Images'

    def __str__(self):
        return f"{self.image}" 


class FAQ(models.Model):
    question = models.TextField('Question')
    answer = models.TextField('Answer')

    class Meta:
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQs'

    def __str__(self):
        return f"{self.question}" 

Tello/core/forms.py
from django import forms
from core.models import *

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author_name', 'author_surname','text']

        widgets = {
            'text': forms.Textarea(attrs={'id': 'question', 'placeholder': 'Rəyinizi buraya yazın', 'class': 'text-input-product'}),
            'author_name': forms.TextInput(attrs={'id': 'question', 'placeholder': 'Adınızı daxil edin', 'class': 'input-product'}),
            'author_surname': forms.TextInput(attrs={'id': 'question', 'placeholder': 'Soyadınızı daxil edin', 'class': 'input-product'})
        }

Tello/core/api/views.py
from rest_framework.generics import CreateAPIView
from core.models import ProductVersion
from .serializers import ProductVersionSerializer

class ProductVersionAPIView(CreateAPIView):
    model = ProductVersion
    serializer_class = ProductVersionSerializer

Tello/core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView , DetailView , CreateView
from core.models import *
from core.forms import *
from django.views.generic.edit import FormMixin
from django.db.models import Q

class MainPageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.filter(category__title="Smartphones").order_by('-id')[:4]
        context['accessories'] = Product.objects.filter(~Q(category__title="Smartphones")).order_by('-id')[:4]
        context['images'] = Image.objects.all()
        return context

class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'list.html'
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['colors'] = Color.objects.all()
        context['images'] = Image.objects.all()
        return context

    def get_queryset(self):
        title = self.request.GET.get('title')
        brand = self.request.GET.get('brand')
        category = self.request.GET.get('category')
        form_factor = self.request.GET.get('form_factor')
        price = self.request.GET.get('price')
        print(price)
        queryset = Product.objects.order_by('-id')

        if title:
            queryset = queryset.filter(title__icontains=title)
        if brand:
            queryset = queryset.filter(brand__icontains=brand)
        if form_factor:
            queryset = queryset.filter(form_factor=form_factor)
        if category:
            queryset = queryset.filter(category__title=category)

        if price and price == '0-500':
            queryset = queryset.filter(price__gte=0).filter(price__lte=500)
        elif price and price == '500-1000':
            queryset = queryset.filter(price__gte=500).filter(price__lte=1000)
        elif price and price == '1000-2000':
            queryset = queryset.filter(price__gte=1000).filter(price__lte=2000)
        elif price and price == '2000':
            queryset = queryset.filter(price__gte=2000)
            print(queryset)
        
        if brand == "all":
            queryset = Product.objects.order_by('-id')

        if title == 'news':
            queryset = Product.objects.order_by('-id')
        elif title == 'cheap':
            queryset = Product.objects.order_by('price')
        elif title == 'expensive':
            queryset = Product.objects.order_by('-price')
        return queryset

class ProductDetailView(FormMixin, DetailView):
    template_name = 'product.html'
    model = Product
    context_object_name = "product"
    form_class = CommentForm

    def get_success_url(self):
        return reverse_lazy('core:product', kwargs={'slug': self.get_object().slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object = self.get_object()
        context['images'] = Image.objects.filter(product=self.object)[1:]
        context['all_images'] = Image.objects.filter(product=self.object)
        return context

    def post(self,request, *args, **kwargs):
        form = self.get_form()
        if request.method == 'POST':
            if request.user.is_authenticated:
                if form.is_valid():
                    self.form_valid(form)
                    return redirect(reverse_lazy('core:product', kwargs={'slug': self.get_object().slug}))

    def form_valid(self, form):
        form.instance.product = self.get_object()
        form.save()
        return super().form_valid(form)

class FAQView(ListView):
    model = FAQ
    template_name = 'faq.html'
    context_object_name = 'faqs'
    queryset = FAQ.objects.all()

Tello/core/templates/includes/footer.html
{% load static %}
<footer class="page-footer font-small mdb-color pt-4" style="color: white;
background: #616060;">

  <!-- Footer Links -->
  <div class="text-center text-md-left" style="padding: 20px;">

    <!-- Footer links -->
    <div class="row text-center text-md-left mt-3 pb-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-3 col-xl-3 mx-auto">
        <a style="margin-bottom: 20px;" class="navbar-brand" href="{% url 'core:main' %}"><img style="width: 140px;" src="{% static 'img/logo-train.png' %}" alt=""></a>
        <div>
          <a href="" class="social-icons"><img src="{% static 'img/instagram.svg' %}" alt=""></a>
          <a href="" class="social-icons"><img src="{% static 'img/facebook.svg' %}" alt=""></a>
          <a href="" class="social-icons"><img src="{% static 'img/youtube.svg' %}" alt=""></a>
          <a href="" class="social-icons"><img src="{% static 'img/twitter.svg' %}" alt=""></a>
        </div>
      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
        <h6 class="mb-4 font-weight-bold">Menu</h6>
        <p>
          <a href="{% url 'core:products' %}" style="color: white; font-weight: 400; font-size: 16px;">Biletlər</a>
        </p>
        <p>
          <a href="{% url 'core:products' %}" style="color: white; font-weight: 400; font-size: 16px;">Bilet al</a>
        </p>
        <p>
          <a href="{% url 'core:products' %}?category=Accessories" style="color: white; font-weight: 400; font-size: 16px;">Tez-tez verilən suallar</a>
        </p>
      </div>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
        <h6 class="mb-4 font-weight-bold">Kömək</h6>
        <p>
          <a href="{% url 'core:faq' %}" style="color: white; font-weight: 400; font-size: 16px;">Tez-tez soruşulan suallar</a>
        </p>
        <!-- <p>
          <a href="#!" style="color: white; font-weight: 400; font-size: 16px;">Shipping Rates</a>
        </p>
        <p>
          <a href="#!" style="color: white; font-weight: 400; font-size: 16px;">Help</a>
        </p> -->
      </div>

      <!-- Grid column -->
      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
        <h6 class="mb-4 font-weight-bold">Əlaqə</h6>
        <p>
          Babek avenue 89, Baku, Azerbaijan</p>
        <p>
         info@gmail.com</p>
        <p>
           +994 55 152 54 54</p>
        <!-- <p>
           + 01 234 567 89</p> -->
      </div>
      <!-- Grid column -->

    </div>
    <!-- Footer links -->

    <hr>

    <!-- Grid row -->
    <div class="row d-flex align-items-center">

      <!-- Grid column -->
      <div class="col-md-7 col-lg-8">

        <!--Copyright-->
        <p class="text-center text-md-left">© 2023 Copyright:
          <a href="https://mdbootstrap.com/">
            <strong style="color: #002e72;"> trainvalet.az</strong>
          </a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-5 col-lg-4 ml-lg-0">

        <!-- Social buttons -->
        <div class="text-center text-md-right">
          <ul class="list-unstyled list-inline">
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                            </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                         </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1">
                             </a>
            </li>
          </ul>
        </div>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

</footer>

Tello/core/templates/includes/navbar.html
{% load static %}
<h1 style="display: none;" id="{{request.user.id}}" class="user-id"></h1>
<nav class="navbar navbar-expand-lg navbar-light pr-5 pt-4 pb-3" style="padding-left: 75px; background-color: #fff;">
    <a class="navbar-brand" href="{% url 'core:main' %}"><img style="width: 140px;" src="{% static 'img/logo-train.png' %}" alt=""></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mt-2 mt-lg-0" style="margin: 0 auto;">
          <form class="form-inline my-2 my-lg-0 nav-form" style="margin-left: 100px;" action="{% url 'core:products' %}">
              <input class="form-control mr-sm-2 nav-inp" name="title" style="width: 591px; height: 40px; background-color: #F7F9FC; border-radius: 7px;" placeholder="Axtarış..." aria-label="Search" value="{{request.GET.title}}">
              <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
            </form>
            <div style="display: flex; margin-left: 113px;" class="nav-iconss">
          <li class="nav-item">

            <div class="dropdown show" style="padding-top: 8px;">
              <a class="btn" href="" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img src="{% static 'img/person.svg' %}" alt="">

              </a>
            
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                {% if request.user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'account:user-profile' user.slug%}">{{request.user}}</a>
                <a class="dropdown-item" href="{% url 'account:log-out' %}">Sign out</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'accounts:login' %}">Sign in</a>
                <a class="dropdown-item" href="{% url 'account:register' %}">Sign up</a>
                {% endif %}
              </div>
            </div>
          </li>
          <!-- <li class="nav-item">
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'accounts:profile-favorites' request.user.slug%}"><img src="{% static 'img/heart.svg' %}" alt=""></a>

                {% else %}
                <a class="nav-link" href="{% url 'accounts:login' %}"><img src="{% static 'img/heart.svg' %}" alt=""></a>

                {% endif %}
          </li> -->
          <li class="nav-item">
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'accounts:cart' request.user.slug%}"><img src="{% static 'img/cart.svg' %}" alt=""> <span style="color: white; background-color: #2DD06E; border-radius: 50%; padding: 1px 5px; font-size: 14px;">{{request.user.user_cart.product_version.all.count}}</span></a>

                {% else %}
                <a class="nav-link" href="{% url 'accounts:login' %}"><img src="{% static 'img/cart.svg' %}" alt=""></a>

                {% endif %}
          </li>
      </div>
        </ul>
        
      </div>
    </nav>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:products' %}" style="color: black;">Biletlər</a>
      </li>
      <li class="nav-item">
        {% if request.GET.brand == 'Baku'%}
        <a class="nav-link" style="color:#2DD06E;" href="{% url 'core:products' %}?brand=Apple">Bilet Al</a>
        {% else %}
        <a class="nav-link" style="color:black;" href="{% url 'core:products' %}?brand=Apple">Bilet Al</a>
        {% endif %}
      </li>
      <li class="nav-item">
        {% if request.GET.brand == 'Samsung'%}
        <a class="nav-link" style="color:#2DD06E;" href="{% url 'core:faq' %}">Tez-tez verilən suallar</a>
        {% else %}
        <a class="nav-link" style="color:black;" href="{% url 'core:faq' %}">Tez-tez verilən suallar</a>
        {% endif %}
      </li>
      <!-- <li class="nav-item">
        {% if request.GET.brand == 'Xiaomi'%}
        <a class="nav-link" style="color:#2DD06E;" href="{% url 'core:products' %}?brand=Xiaomi">Xiaomi</a>
        {% else %}
        <a class="nav-link" style="color:black;" href="{% url 'core:products' %}?brand=Xiaomi">Xiaomi</a>
        {% endif %}
      </li>
      <li class="nav-item">
        {% if request.GET.brand == 'Redmi'%}
          <a class="nav-link" style="color:#2DD06E;" href="{% url 'core:products' %}?brand=Redmi">Redmi</a>
        {% else %}
        <a class="nav-link" style="color:black;" href="{% url 'core:products' %}?brand=Redmi">Redmi</a>
        {% endif %}

        </li> -->
        <!-- <li class="nav-item">
          {% if request.GET.brand == 'all'%}
          <a class="nav-link" style="color:#2DD06E;" href="{% url 'core:products' %}?brand=all">Butun brendler</a>
          {% else %}
          <a class="nav-link" style="color:black;" href="{% url 'core:products' %}?brand=all">Butun brendler</a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if request.GET.category == 'Accessories'%}
          <a class="nav-link" style="color:#2DD06E;" href="{% url 'core:products' %}?category=Accessories">Aksessuarlar</a>
          {% else %}
          <a class="nav-link" style="color:black;" href="{% url 'core:products' %}?category=Accessories">Aksessuarlar</a>
          {% endif %}
        </li> -->
        <!-- <li class="nav-item">
          <a class="nav-link" style="color:black;" href="#">Endirimler</a>
        </li> -->
    </ul>

Tello/core/templates/includes/navbar2.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light pr-5 pt-4 pb-4" style="display: flex; justify-content: center; border-bottom: 1px solid #2DD06E;">

        <a class="navbar-brand" href="{% url 'core:main' %}"><img style="width: 140px;" src="{% static 'img/Artboard 1 copy 9@2x.svg' %}" alt=""></a>


    
</nav>