Tello/Tello/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls',namespace = 'core')),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('api/v1/', include('accounts.api.urls')),
    path('api/v1/core/', include('core.api.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tello/accounts/api/urls.py
from django.urls import path
from .views import *

app_name = 'accounts_api'

urlpatterns = [
    # path('change-password/<int:id>/', ChangePasswordView.as_view(), name='change-password'),
    path('add-to-wishlist/', AddToWishlist.as_view(), name='add-to-wishlist'),
    path('remove-from-wishlist/', RemoveFromWishlist.as_view(), name='remove-from-wishlist'),
    path('add-to-cart/', AddToCart.as_view(), name='add-to-cart'),
    path('remove-from-cart/', RemoveFromCart.as_view(), name='remove-from-cart'),
]

Tello/accounts/urls.py
from django.urls import path
from core.views import *
from accounts.views import *
from django.contrib.auth.views import LogoutView

app_name = 'account'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('profile/<slug:slug>/', UserProfileView.as_view(), name='user-profile'),
    path('change-password/', UpdatePasswordView.as_view(), name='change-password'),
    path('wishlist/<slug:slug>/', UserWishlistView.as_view(), name='profile-favorites'),
    path('cart/<slug:slug>/', UserCartView.as_view(), name='cart'),
    path('create-order/<slug:slug>/', CreateOrderView.as_view(), name='create-order'),
    path('success/', SuccessPageView.as_view() ,name ='success'),
    path('register/', usersignup,name ='register'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate_account, name='activate'),
    path('log-out', LogoutView.as_view(), name='log-out'),
]

Tello/core/urls.py
from django.urls import path
from core.views import *
# from django.contrib.auth.views import LogoutView

app_name = 'core'

urlpatterns = [
    path('',MainPageView.as_view(),name ='main'),
    path('products/',ProductListView.as_view(),name ='products'),
    path('product/<slug:slug>', ProductDetailView.as_view(), name='product'),
    path('faq/', FAQView.as_view(), name='faq'),
]

Tello/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, UnicodeUsernameValidator
from core.common import slugify
from .managers import UserManager
from core.models import Product, ProductVersion
# from django.core.mail import send_mail

from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator
    username = models.CharField(
        ('username'),
        max_length=150,
        blank=True,
        null=True,
        unique=False,
        help_text=('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': ("A user with that username already exists."),
        },
    )
    email = models.EmailField(('email adress'), unique=True)
    full_name = models.CharField(max_length=100)
    number = models.CharField(max_length=100, null=True, blank=True)
    slug = models.SlugField(max_length=255, null=True, blank=True)
    birth_date = models.DateTimeField(null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return f"{self.email}"

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)
        self.slug = f'{slugify(self.full_name)}-{self.id}'
        super(User, self).save(*args, **kwargs)


class Wishlist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, db_index=True, related_name='user_wishlist')
    product = models.ManyToManyField(Product, verbose_name=("Product"), db_index=True, related_name='wishlist_product', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Wishlist'
        verbose_name_plural = 'Wishlists'

    def __str__(self):
        return f"{self.user.email}'s Wishlist"


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, db_index=True, related_name='user_cart')
    product_version = models.ManyToManyField(ProductVersion, verbose_name=("Product Version"), db_index=True, related_name='cart_product', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Cart'
        verbose_name_plural = 'Carts'
    
    def __str__(self):
        return f"{self.user.email}'s Cart"

    def get_price_summary(self):
        price = 0
        for product in self.product_version.all():
            price += product.product.price
        return price

class Order(models.Model):
    PAYMENT_CHOICES = (
    ("Onlayn kart ilə ödəmə", ("Onlayn kart ilə ödəmə")),
    ("Qapıda nağd ödəmə", ("Qapıda nağd ödəmə"))
)
    customer_name = models.CharField(max_length=100)
    customer_surname = models.CharField(max_length=100)
    customer_number = models.CharField(max_length=100)
    customer_adress = models.CharField(max_length=1000)
    customer_home_number = models.CharField(max_length=50)
    message_for_courier = models.TextField('Message for courier')
    payment_type = models.CharField(choices=PAYMENT_CHOICES, max_length=6000)
    customer_email = models.EmailField(('Email adress'), unique=False)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, db_index=True, related_name='cart_order', null=True, blank=True)
    final_price = models.IntegerField('Final price',blank=True,null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return f"Sifarişçi: {self.customer_name} {self.customer_surname}  Məbləğ: {self.final_price} AZN"

Tello/accounts/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm,UsernameField
from .models import User, Order
from django.contrib.auth.forms import PasswordChangeForm

PAYMENT_CHOICES = (
    ("Onlayn kart ilə ödəmə", ("Onlayn kart ilə ödəmə")),
    ("Qapıda nağd ödəmə", ("Qapıda nağd ödəmə"))
)


class RegisterForm(UserCreationForm):

    password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'password',
                'class' : 'fullname-inp',
            }))

    password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'confirm password',
                'class' : 'fullname-inp',
            }))

    class Meta:
        model = User
        fields = ('full_name','email','password1','password2', 'number')

        widgets = {
            'full_name': forms.TextInput(attrs={'id': 'fullname', 'placeholder': 'Ad və soyadınızı daxil edin', 'class': 'fullname-inp'}),
            'email': forms.EmailInput(attrs={'id': 'email', 'placeholder': 'nümunə@gmail.com', 'class': 'fullname-inp'}),
            'number': forms.NumberInput(attrs={'id': 'phone', 'placeholder': '000-00-00', 'class': 'fullname-inp'}),
        }


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={
        'autofocus': True,
        'class': 'fullname-inp',
        'placeholder': 'Email',
        'name': 'email'
    }))
    password = forms.CharField(
        label=("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'current-password',
            'class': 'fullname-inp',
            'name': 'password',
            'placeholder': 'Password'
        }),
    )

    class Meta:
        model = User
        fields = ['username', 'password']

class UpdateProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['full_name', 'email', 'number', 'birth_date']

        widgets = {
            'full_name': forms.TextInput(attrs={'id': 'full_name', 'placeholder': 'First Name',  'class': 'profile-infp-inp'}),
            'email': forms.EmailInput(attrs={'id': 'email', 'placeholder': 'Bio',  'class': 'profile-infp-inp'}),
            'number': forms.NumberInput(attrs={'id': 'phone', 'placeholder': '123-456-7890', 'class': 'profile-infp-inp', 'pattern': '[0-9]{3}-[0-9]{2}-[0-9]{3}'}),
            'birth_date': forms.DateInput(attrs={'id': 'date', 'placeholder': '2021-10-30', 'class': 'profile-infp-inp'}),
        }

class ThePasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Cari şifrənizi daxil edin',
                'class' : 'profile-infp-inp',
            }))

    new_password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Yeni şifrənizi daxil edin',
                'class' : 'profile-infp-inp',
            }))

    new_password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Yeni şifrənizi yenidən daxil edin',
                'class' : 'profile-infp-inp',
            }))

class CreateOrderForm(forms.ModelForm):
    payment_type = forms.ChoiceField(choices=PAYMENT_CHOICES,
    widget=forms.RadioSelect)

    class Meta:
        model = Order
        fields = ['customer_name', 'customer_surname', 'customer_number', 'customer_adress', 'customer_home_number', 'message_for_courier', 'customer_email', 'payment_type']

        widgets = {
            'customer_name': forms.TextInput(attrs={'id': 'first_name', 'placeholder': 'Adınızı daxil edin',  'class': 'payment-inputs'}),
            'customer_surname': forms.TextInput(attrs={'id': 'last_name', 'placeholder': 'Soyadınızı daxil edin',  'class': 'payment-inputs'}),
            'customer_number': forms.TextInput(attrs={'id': 'number', 'placeholder': '000 - 00 - 00',  'class': 'payment-inputs'}),
            'customer_adress': forms.TextInput(attrs={'id': 'customer_adress', 'placeholder': 'Ünvanı daxil edin',  'class': 'payment-inputs'}),
            'customer_home_number': forms.TextInput(attrs={'id': 'customer_home_number', 'placeholder': 'Daxil edin',  'class': 'payment-inputs'}),
            'message_for_courier': forms.Textarea(attrs={'id': 'message_for_courier', 'placeholder': 'Mətni daxil edin...',  'class': 'payment-textarea'}),
            'customer_email': forms.EmailInput(attrs={'id': 'email', 'placeholder': 'nümunə@gmail.com',  'class': 'payment-inputs'}),
        }

Tello/accounts/api/views.py
from rest_framework import generics
from rest_framework.response import Response
# from django.contrib.auth.models import User
from rest_framework.views import APIView
from . import serializers
from rest_framework.permissions import IsAuthenticated   
from rest_framework.generics import UpdateAPIView
from .serializers import ChangePasswordSerializer
from rest_framework import status
from core.models import Product, ProductVersion
from accounts.models import User

class AddToWishlist(APIView):
    def post(self, request, *args, **kwargs):
        product_id = self.request.data.get('product')
        user_id = self.request.data.get('user')
        product = Product.objects.get(pk=int(product_id))
        user = User.objects.get(pk=int(user_id))
        user.user_wishlist.product.add(product)
        return Response("Added to Wishlist")

class RemoveFromWishlist(APIView):
    def post(self, request, *args, **kwargs):
        product_id = self.request.data.get('product')
        user_id = self.request.data.get('user')
        product = Product.objects.get(pk=int(product_id))
        user = User.objects.get(pk=int(user_id))
        user.user_wishlist.product.remove(product)
        return Response("Removed from Wishlist")

class AddToCart(APIView):
    def post(self, request, *args, **kwargs):
        product_id = self.request.data.get('product')
        user_id = self.request.data.get('user')
        product = ProductVersion.objects.get(pk=int(product_id))
        user = User.objects.get(pk=int(user_id))
        user.user_cart.product_version.add(product)
        return Response("Added to Cart")

class RemoveFromCart(APIView):
    def post(self, request, *args, **kwargs):
        product_id = self.request.data.get('product')
        user_id = self.request.data.get('user')
        product = ProductVersion.objects.get(pk=int(product_id))
        user = User.objects.get(pk=int(user_id))
        user.user_cart.product_version.remove(product)
        return Response("Removed from Cart")

Tello/accounts/views.py
from decimal import Context
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from accounts.forms import RegisterForm, LoginForm, CreateOrderForm
from django.views.generic import TemplateView, ListView , DetailView , CreateView, UpdateView
from accounts.models import User, Wishlist, Cart, Order
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.views.generic.edit import FormMixin
from .forms import *

def usersignup(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            wishlist = Wishlist.objects.create(user=user)
            cart = Cart.objects.create(user=user)
            

            current_site = get_current_site(request)
            email_subject = 'Activate Your Account'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': force_text(urlsafe_base64_encode(force_bytes(user.pk))),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(email_subject, message, to=[to_email])
            email.send()
            return render(request, 'index.html')
    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form': form})

def activate_account(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return render(request, 'index.html')
    else:
        return HttpResponse('Activation link is invalid!')


class LoginUserView(LoginView):
    template_name = 'login.html'
    form_class = LoginForm

# class UserProfileView(DetailView):
#     template_name = 'profile-info.html'
#     model = User
#     context_object_name = "user"

class UserProfileView(UpdateView):
    model = User
    template_name = 'profile-info.html'
    form_class = UpdateProfileForm
    success_url = reverse_lazy('core:index')

    def get_success_url(self):
        return reverse_lazy('account:user-profile', kwargs={'slug':self.get_object().slug})

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.username != self.get_object().username:
            raise PermissionDenied
        return super(UserProfileView, self).dispatch(request, *args, **kwargs)

class UpdatePasswordView(PasswordChangeView):
    template_name = 'reset-password.html'
    form_class = ThePasswordChangeForm
    success_url = reverse_lazy('accounts:login')


class UserWishlistView(DetailView):
    template_name = 'profile-favorites.html'
    context_object_name = "user"
    model = User

class UserCartView(DetailView):
    template_name = 'cart.html'
    context_object_name = "user"
    model = User

class CreateOrderView(FormMixin, DetailView):
    template_name = 'payment-process.html'
    model = User
    context_object_name = "user"
    form_class = CreateOrderForm
    success_url = reverse_lazy('accounts:success')

    def post(self,request, *args, **kwargs):
        form = self.get_form()
        if request.method == 'POST':
            if request.user.is_authenticated:
                if form.is_valid():
                    return self.form_valid(form)

    def form_valid(self, form):
        form.instance.cart = self.request.user.user_cart
        form.instance.final_price = self.request.user.user_cart.get_price_summary()
        form.save()
        for product in self.request.user.user_cart.product_version.all():
            self.request.user.user_cart.product_version.remove(product)
        return super().form_valid(form)

class SuccessPageView(TemplateView):
    template_name = 'success.html'

Tello/accounts/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.full_name }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

Tello/accounts/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/checkboxes.css' %}">
    <link rel="stylesheet" href="{% static 'slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'slick/slick-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <style>
        .profile-infp-inp {
            background: #F2F2F2;
                                    border-radius: 8px;
                                    width: 279px;
                                    height: 48px;
                                    opacity: 1;
                                    position: inherit;
                                    border: none;
                                    padding-left: 16px;
        }
        .slick-next,
        .slick-prev {
            background-color: rgb(209, 202, 202);
            border-radius: 50%;
            width: 50px;
            height: 50px;
            z-index: 1;
        }

        .slick-next:hover,
        .slick-prev:hover {
            background-color: rgb(77, 52, 52);

        }

        .slick-next:focus,
        .slick-prev:focus {
            background-color: rgb(68, 63, 63);

        }

        .slick-slide {
            margin: 0 10px;
        }

        .card-header {
            background-color: transparent;
        }

        .btn-link {
            color: #4F4F4F;
        }

        .btn-link:hover {
            color: #4F4F4F;
            text-decoration: none;
        }
        .page-link {
            margin-left: 32px;
        }
        .page-item:first-child .page-link {
            margin-left: 0;
            border-radius: 50%;
            width: 36px;
            height: 36px;
        }
        .page-item:last-child .page-link {
            border-radius: 50%;
            width: 36px;
            height: 36px;
}
.num {
    border: none;
}
.card {
    filter: drop-shadow(0px 2px 16px rgba(130, 130, 130, 0.07));
    border: transparent;
    border-radius: 8px;
    box-shadow:none !important;
    background-color: 
white;
}
.card-header {
    border-bottom: none;
}

@media (min-width: 361px) and (max-width: 767px) {
    .empty-cont {
        display: flex;
        justify-content: initial !important;
    }
    .blocks-cont {
        padding-left: 0 !important;
        padding-right: 0 !important;
    }
    .personal-info {
        margin-right: 5px !important;
    }
    .block-1-img-cont {
        text-align: center;
    }
    .order-block-1 {
        display: block !important;
    }
    .profile-inputs-cont {
        display: block !important;
    }
    }
 @media (max-width: 360px) {
    .empty-cont {
        display: flex;
        justify-content: initial !important;
    }
    .blocks-cont {
        padding-left: 0 !important;
        padding-right: 0 !important;
    }
    .personal-info {
        margin-right: 5px !important;
    }
    .block-1-img-cont {
        text-align: center;
    }
    .order-block-1 {
        display: block !important;
    }
    .profile-inputs-cont {
        display: block !important;
    }
    }
 @media (min-width: 768px) and (max-width: 841px) {
    
    .empty-cont {
        display: flex;
        justify-content: initial !important;
    }
    .blocks-cont {
        padding-left: 0 !important;
        padding-right: 0 !important;
    }
    .personal-info {
        margin-right: 5px !important;
    }
    .block-1-img-cont {
        text-align: center;
    }
    .order-block-1 {
        display: block !important;
    }
    .profile-inputs-cont {
        display: block !important;
    }
    }
    </style>
    {% endblock %}

    {% block content %}
    <div class="profile-main" style="background-color: #FAF9F9; padding-bottom: 158px;">
        <div class="container-fluid">
            <div class="row">
                <!-- <div class="col-md-3 sections-cont" style="margin-top: 40px; padding-left: 73px;">
                    <div class="profile-sections" style="width: 280px; background-color: white; border-radius: 8px; padding-top: 32px; padding-left: 26px; padding-bottom: 32px;">
                        <h5 style="font-size: 20px; padding-bottom: 32px; color: #4F4F4F;">Profilim</h5>
                        <div>
                            <ul style="padding-left: 0;">
                                <a href="" style="text-decoration: none;"><li style="list-style: none; margin-bottom: 32px;"><img style="margin-right: 16px;" src="{% static 'img/cart.svg' %}" alt=""><span style="color: #4F4F4F;">Sifarişlərim</span></li></a>
                                <a href="{% url 'accounts:profile-favorites' request.user.slug%}" style="text-decoration: none;"><li style="list-style: none; margin-bottom: 32px;"><img style="margin-right: 16px;" src="{% static 'img/heart-gree.svg' %}" alt=""><span style="color: #2DD06E;">Favorilərim</span></li></a>
                                <a href="{% url 'accounts:user-profile' request.user.slug%}" style="text-decoration: none;"><li style="list-style: none; margin-bottom: 32px;"><img style="margin-right: 16px;" src="{% static 'img/person.svg' %}" alt=""><span style="color: #4F4F4F;">Şəxsi məlumatlar</span></li></a>
                                <a href="" style="text-decoration: none;"><li style="list-style: none; margin-bottom: 32px;"><img style="margin-right: 16px;" src="{% static 'img/pin.svg' %}" alt=""><span style="color: #4F4F4F;">Çatdırılma ünvanı</span></li></a>
                                <a href="{% url 'accounts:change-password' %}" style="text-decoration: none;"><li style="list-style: none; margin-bottom: 32px;"><img style="margin-right: 16px;" src="{% static 'img/person.svg' %}" alt=""><span style="color: #4F4F4F;">Şifrəni yenilə</span></li></a>
                                <a href="" style="text-decoration: none;"><li style="list-style: none;"><img style="margin-right: 16px;" src="{% static 'img/log-out.svg' %}" alt=""><span style="color: #4F4F4F;">Çıxış</span></li></a>
                            </ul>
                        </div>
                    </div>
                </div> -->
                <div class="col-md-8 profile-cards-cont" style="margin-top: 40px; padding-left: 34px;">
                    <div class="profile-names-cont">
                        <h4 class="profile-name-mobile" style="margin-bottom: 16px; color: #4F4F4F;">Profilim</h4>
                        <h5 style="font-size: 20px; padding-bottom: 32px; color: #4F4F4F; margin-top: 9px;">Səbət ({{user.user_cart.product_version.all.count}} məhsul)</h5>
                    </div>
                    
                    
                   
                    {% if user.user_cart.product_version.all.count != 0 %}
                    <div class="row favs-list">
                        {% for product in user.user_cart.product_version.all %}
                    <div class="col-md-12" style="margin-bottom: 40px;">
                        <div class="card" style="display: flex;">
                          
                            <div class="d-flex" style="padding: 10px;">
                                {% for image in product.product.product_image.all|slice:"1" %}
                                <img class="card-img-top" style="width: 115px;" src="/media/{{image}}" alt="Card image cap">
                                {% endfor %}
                                <div class="card-body" style="padding-top: 30px;">
                                    <div class="d-flex">
                                        <div>
                                            <h5 class="card-title" style="font-size: 16px;">{{product.product.brand}} {{product.product.title}}</h5>
                                    
                                            <p class="card-text">Rəng: <span style="text-transform: capitalize;">{{product.color}}</span></p>
    
                                        </div>
                                                                                
                                        <div style="margin-left: 100px; margin-top: 15px;">
                                            {{product.get_final_price}}<img style="margin-top: -5px;" src="{% static 'img/azn.svg' %}" alt="">
                                        </div>
                                        <div style="margin-left: 70px; margin-top: 15px; color: #2DD06E;">
                                            {{product.quantity}} ədəd
                                        </div>
                                    </div>
                                    
                                  </div>
                                  
                                  <div class="heart-cont" style="display: flex;
                          justify-content: end; align-items: center;">
                            <div style="border: 1px solid #F2F2F2; border-radius: 50%;
                            height: 40px;
                            width: 40px;
                            margin-right: 10px;">
                              <img class="delete-button" itsfor="{{product.pk}}" src="{% static 'img/delete.svg' %}" alt="" style="margin-top: 7px; margin-left: 10px;">

                            </div>
                          </div>
                        </div>
                            
                          </div>
                    </div>
                  {% endfor %}
                </div>
                    {% else %}
                     <div class="empty-cont">
                        <div style="background-color: white; text-align: center;height: 371px;">
                            <img src="{% static 'img/heart-empty.svg' %}" style="margin-top: 103px;" alt="">
                            <p style="color: #BDBDBD; margin-top: 40px;">Səbətinizdə hazırda heç bir məhsul yoxdur</p>
                        </div>
                    </div>
                    {% endif %}
                    
                </div>
                <div class="col-md-4" style="margin-top: 106px;">
                    <div class="card payment-card" style="width: 344px; padding: 32px; margin: 0 auto;">
                        <div style="border-bottom: 1px solid #828282;">
                            <h6 style="font-size: 20px; margin-bottom: 16px;">Ümumi</h6>
                            <div style="display: flex; justify-content: space-between; margin-bottom: 16px;">
                                <span style="font-size: 16px;">Məbləğ</span>
                                <span style="font-size: 16px;">{{user.user_cart.get_price_summary}} <img style="margin-top: -5px;" src="{% static 'img/azn.svg' %}" alt=""></span>
                            </div>
                            <div style="display: flex; justify-content: space-between; margin-bottom: 16px;">
                                <span style="font-size: 16px;">Promo kod</span>
                                <span style="font-size: 16px;">-0.00 <img style="margin-top: -5px;" src="{% static 'img/azn.svg' %}" alt=""></span>
                            </div>
                        </div>
                        <div style="display: flex; justify-content: space-between; margin-top: 16px;">
                            <span style="font-size: 16px;">Cəmi</span>
                            <span style="font-size: 16px;">{{user.user_cart.get_price_summary}} <img style="margin-top: -5px;" src="{% static 'img/azn.svg' %}" alt=""></span>
                        </div>

                        <a href="{% url 'accounts:create-order' user.slug%}"><input type="submit" value="Məhsullari əldə et" style="margin-top: 22px; background-color: #2DD06E; border: none; border-radius: 8px; padding: 16px 80px; color: white;"></a>
                       
                       
                    </div>
                </div>
            </div>
        </div>

    </div>
    {% endblock %}

    {% block js %}
    <script src="{% static 'js/delete-from-cart.js' %}"></script>
    {% endblock %}